### ISSUE TITLE
Installation instructions - trouble

### ISSUE THREAD

**Issue by kurlberg** [odlgroup/odlworkshop#29]
When following the official documentation at

https://github.com/adler-j/odlworkshop/blob/master/code/part0_install.ipynb

(on radon) I get the following error when testing tensorflow (the install proceeded ok.) Possibly radon is out of wack, but no luck with gelfand either (it's out of disk space.)

>>>> import tensorflow
> Traceback (most recent call last):
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>    from tensorflow.python.pywrap_tensorflow_internal import *
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>    _pywrap_tensorflow_internal = swig_import_helper()
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>  File "/home/kurlberg/anaconda3/lib/python3.6/imp.py", line 243, in load_module
>    return load_dynamic(name, filename, file)
>  File "/home/kurlberg/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
>    return _load(spec)
> ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
>    from tensorflow.python import *
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>    from tensorflow.python import pywrap_tensorflow
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 73, in <module>
>    raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>    from tensorflow.python.pywrap_tensorflow_internal import *
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>    _pywrap_tensorflow_internal = swig_import_helper()
>  File "/home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>  File "/home/kurlberg/anaconda3/lib/python3.6/imp.py", line 243, in load_module
>    return load_dynamic(name, filename, file)
>  File "/home/kurlberg/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
>    return _load(spec)
> ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/kurlberg/anaconda3/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/install_sources#common_installation_problems
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
>>>>

**Comment by adler-j** [comment]
Did you try installing tensorflow yourself on radon? Because it is pre-installed for you and you shouldn't need to do anything, at least if you use the jupyterhub setup.

If you run the installation manually, it seems this is exactly this error: https://github.com/ContinuumIO/anaconda-issues/issues/483

I've never had it myself, but it seems one solution is to run `conda install libgcc` but it doesn't seem to work for everyone.

**Comment by adler-j** [comment]
Also a possibility (depending on where you installed TF from) is that it is related to this:

https://github.com/lakshayg/tensorflow-build/issues/1

**Comment by kurlberg** [comment]
I uninstalled "my" tensorflow, and ran "import tensorflow", both with and
without jupyter, and it barfs (see below.)

BTW, "locate tensorflow" on radon only finds stuff in /mnt/datahd (there's
lots of stuff in /home though.)



---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

ModuleNotFoundError: No module named 'tensorflow'
